stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sartography/cr-connect-bpmn:latest
      pushRemote: true
      registry: docker-registry.crc.sartography.com:5000
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification:
  recipients:
  - recipient: fred@frameworklabs.us
    notifier: c-dl5v7:n-6w5dl
  condition:
  - Success
  - Changed
  - Failed
