stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sartography/cr-connect-bpmn:latest
      pushRemote: true
      registry: docker-registry.crc.sartography.com:5000
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
